# Generated by Django 5.2.7 on 2025-11-22 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Marvel Heroes')", max_length=100)),
               ('team_names', models.TextField(default='[]',help_text='JSON encoded list of team names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, help_text='Mark this template as the default selection')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.TextField(help_text='CSV content as text')),
                ('team_size', models.IntegerField(help_text='People per team')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_count', models.IntegerField(help_text='Total number of students')),
                ('template_used', models.ForeignKey(blank=True, help_text='Team name template used (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_side.teamnametemplate')),
            ],
            options={
                'verbose_name': 'CSV Generation',
                'verbose_name_plural': 'CSV Generations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
