# Generated by Django 6.0.5 on 2026-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_side', '0003_rename_name_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='commitment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lead_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
# Generated by Django 4.2.30 on 2026-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_side", "0003_rename_name_studentprofile_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="commitment",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="experience_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="lead_preference",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
